name: Production Deployment Workflow
on:
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    prod-deployment:
        name: Production Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Deploy to Production
              uses: tythonco/actions-sfdx@master
              with:
                  auth_file_key: ${{ secrets.AUTH_FILE_KEY }}
                  command: deploy
                  enc_auth_file: prod_auth_url.txt.enc
                  test_level: RunLocalTests
